site_name: Entornos de desarrollo y sintaxis de python
site_url: ""
site_dir: ../site
docs_dir: docs
use_directory_urls: false
theme:
  language: es
  favicon: images/favicon.ico
  name: material
  palette:
    primary: light blue
    accent: "Teal"
  font:
    text: Roboto
    code: Roboto Mono
  logo: images/favicon.ico
  features:
    - header.autohide

nav:
  - "index.md"
  - 1. Iniciación a Python: 
    - Introducción: "introduccion/introduccion.md"
    - Historia de Python: "introduccion/historia.md"
  - 2.Entornos de desarrollo:
    - Introducción: "entornos/introduccion.md"
    - IDEs para Python: "entornos/ides.md"
    - Entornos de ejecución: "entornos/entornos.md"
  - 2. Entornos de aprendizaje:
    - Introducción: "aprendizaje/introduccion.md"
    - Aprendizaje basico: "aprendizaje/basico.md"
    - Aprendizaje medio: "aprendizaje/medio.md"
    - Aprendizaje avanzado : "aprendizaje/avanzado.md"
  - 3. Entornos cloud:
    - Introducción: "cloud/introduccion.md"
    - Jupyter Notebook: "cloud/jupyter.md"
    - Google Colab: "cloud/colab.md"
    - SageMaker: "cloud/sagemaker.md"
    - Kaggle: "cloud/kaggle.md"
  - 4. Entornos dockerizados:
    - Introducción: "docker/introduccion.md"
    - Docker: "docker/docker.md"
    - Docker Compose: "docker/compose.md"
    - Visual Studio Code: "docker/vscode.md"
extra:
  search:
    language: "es"

plugins: []

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.critic
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - footnotes
  - meta
  - sane_lists
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic

extra_javascript:
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
 
